#!/bin/sh
case "$1" in
# we only allow executing these commands
useradd|usermod|userdel|groupadd|groupmod|groupdel)
    # TODO: platforms using different commands can add workarounds here.
    exec $*
    ;;
*)
    echo "Command '$1' is not allowed!"
    exit 1
    ;;
esac
