#!/bin/sh
case "$1" in
# we only allow executing these commands
useradd|usermod|userdel|groupadd|groupmod|groupdel|passwd|gpasswd)
    export LC_ALL=C
    exec "$@"
    ;;
pw)
    case "$2" in
    useradd|usermod|userdel|groupadd|groupmod|groupdel)
        export LC_ALL=C
        exec "$@"
        ;;
        *)
        echo "Command '$1' '$2' is not allowed"
        exit 1
        ;;
    esac
    ;;
*)
    echo "Command '$1' is not allowed!"
    exit 1
    ;;
esac
